# Config for site

# Header title
name: Madelon Hulsebos

# Author name
author: Madelon Hulsebos

# URL of profile picture
avatar: /images/madelon-hs.jpeg

footer-links:
  email: madelon@berkeley.edu
  github: madelonhulsebos
  linkedin: madelonhulsebos
  twitter: MadelonHulsebos
  googlescholar: 6IWQn2EAAAAJ

# Used for Sitemap.xml and your RSS feed
url: http://madelonhulsebos.github.io
enforce_ssl: https://madelonhulsebos.github.io

permalink: /:title/

# The release of Jekyll
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory
sass:
  style: :compressed # versus expand

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

gems:
  - jemoji

collections:
  talks:
    output: false
  projects:
    output: true
  trl:
    output: true
  upcoming:
    output: true

include: ['_pages', '_pages', 'images/']

paginate: 3
paginate_path: /news/page:num/

# Google Analytics
google_analytics: G-3JGXB637F3

# Exclude these files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

